ARG FEDORA_VERSION
ARG LIBATION_VERSION

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

ARG LIBATION_VERSION

LABEL org.opencontainers.image.description="A toolbox for running Libation."
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.source=https://github.com/tristankretzer/toolboxes

RUN wget -O /tmp/libation.rpm \
         https://github.com/rmcrackan/Libation/releases/download/v${LIBATION_VERSION}/Libation.${LIBATION_VERSION}-linux-chardonnay-amd64.rpm \
    && dnf -y update \
    && dnf -y install gtk-update-icon-cache libicu /tmp/libation.rpm \
    && dnf clean all \
    && rm -f /tmp/libation.rpm
