name: Libation

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
    paths:
      - images/libation/**
      - .github/workflows/libation.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/toolbox-libation

jobs:
  build:
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        fedora_version: ["42"]
        libation_version: ["12.4.7"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=fedora-${{matrix.fedora_version}}-libation-${{matrix.libation_version}}

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.12
        with:
          context: images/libation
          containerfiles: |
            images/libation/Containerfile
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FEDORA_VERSION=${{matrix.fedora_version}}
            LIBATION_VERSION=${{matrix.libation_version}}
          oci: true

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
